# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action


name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots

      - name: Merge test reports
        run: npm run combine:report

      - name: Generate HTML report
        run: npm run generate:report
      
          
